name: Python Linting Workflow

on:
  push:
    branches: [main]

jobs:
  lint-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run flake8 on hello.py
        run: flake8 hello.py --max-line-length=79 --exit-zero

      - name: Run hello.py
        run: python hello.py
